//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Compact.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetSubcategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetSubcategory()
        {
            this.Asset = new HashSet<Asset>();
        }
    
        public System.Guid SubcategoryKey { get; set; }
        public string SubcategoryName { get; set; }
        public string SubcategoryID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.Guid> CategoryKey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset> Asset { get; set; }
        public virtual AssetCategory AssetCategory { get; set; }
    }
}
