//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Compact.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public System.Guid CustomerKey { get; set; }
        public System.Guid WarehouseKey { get; set; }
        public string CustomeID { get; set; }
        public string CustomerName { get; set; }
        public string CustomeAddress { get; set; }
        public string CPhone { get; set; }
        public string CMobile { get; set; }
        public string CEmail { get; set; }
        public string CWebsite { get; set; }
        public string CFax { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactPersonNo { get; set; }
        public byte[] Logo { get; set; }
        public string LogoType { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<decimal> DiscountPerc { get; set; }
        public Nullable<decimal> DiscountAmt { get; set; }
        public Nullable<decimal> Incentive { get; set; }
        public Nullable<System.Guid> UpazillaKey { get; set; }
    
        public virtual Upazilla Upazilla { get; set; }
    }
}
