//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Compact.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public System.Guid TaxKey { get; set; }
        public string TaxID { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public Nullable<System.Guid> WarehouseKey { get; set; }
    }
}
