//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Compact.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsergroupToSubmodule
    {
        public System.Guid GroupToSubModuleKey { get; set; }
        public Nullable<System.Guid> SubModuleID { get; set; }
        public Nullable<System.Guid> GroupKey { get; set; }
    
        public virtual SubModule SubModule { get; set; }
        public virtual Usergroup Usergroup { get; set; }
    }
}
