//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Compact.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public System.Guid WarehouseKey { get; set; }
        public string WahouseID { get; set; }
        public string WahouseName { get; set; }
        public string WahouseAddress { get; set; }
        public string WahousePhone { get; set; }
        public string WahouseMobile { get; set; }
        public string WahouseEmail { get; set; }
        public string WahouseWebsite { get; set; }
        public string WahouseFax { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactPersonNo { get; set; }
        public byte[] Logo { get; set; }
        public string LogoType { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.Guid> DivisionKey { get; set; }
        public Nullable<System.Guid> DistrictKey { get; set; }
        public Nullable<System.Guid> UpazillaKey { get; set; }
    
        public virtual District District { get; set; }
        public virtual Division Division { get; set; }
        public virtual Upazilla Upazilla { get; set; }
    }
}
